from gTTS import gTTS
from fpdf import FPDF
import io

class ReportEngine:
    def execute_audio_briefing(self, text_content):
        """
        Generates an MP3 audio bytes object from text.
        """
        try:
            tts = gTTS(text=text_content, lang='en', tld='co.in') # Indian accent
            mp3_fp = io.BytesIO()
            tts.write_to_fp(mp3_fp)
            return mp3_fp.getvalue()
        except Exception as e:
            return None

    def generate_pdf_report(self, data):
        """
        Generates a High-Tech PDF Safety Certificate.
        """
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Arial", 'B', 20)
        pdf.set_text_color(0, 51, 102) # Dark Blue
        pdf.cell(0, 10, "OPTIFRESH BIO-SAFETY CERTIFICATE", ln=True, align='C')
        
        pdf.set_font("Arial", 'I', 10)
        pdf.cell(0, 10, "Automated Neural Inspection Report", ln=True, align='C')
        
        pdf.line(10, 30, 200, 30)
        pdf.ln(15)
        
        # Item Details
        pdf.set_font("Arial", 'B', 14)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, f"Subject: {data.get('item', 'Unknown Entity')}", ln=True)
        
        pdf.set_font("Arial", '', 12)
        pdf.cell(0, 10, f"Detected Freshness: {data.get('freshness', 0):.1f}%", ln=True)
        pdf.cell(0, 10, f"Spoilage Verdict: {data.get('verdict', 'N/A')}", ln=True)
        pdf.cell(0, 10, f"Confident Score: {data.get('confidence', 0):.2f}", ln=True)
        
        pdf.ln(10)
        
        # Safety Declaration
        if data.get('freshness', 0) > 70:
            pdf.set_fill_color(200, 255, 200) # Green
            pdf.cell(0, 15, "SAFE FOR CONSUMPTION", ln=True, align='C', fill=True)
        elif data.get('freshness', 0) > 40:
            pdf.set_fill_color(255, 255, 200) # Yellow
            pdf.cell(0, 15, "CONSUME WITH CAUTION", ln=True, align='C', fill=True)
        else:
            pdf.set_fill_color(255, 200, 200) # Red
            pdf.cell(0, 15, "BIO-HAZARD: DO NOT EAT", ln=True, align='C', fill=True)
            
        pdf.ln(20)
        pdf.set_font("Courier", '', 10)
        pdf.multi_cell(0, 5, "This document was generated by OPTIFRESH V2. Analysis is based on computer vision and is probabilistic. Always use sensory verification.")
        
        return pdf.output(dest='S').encode('latin-1')
